language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

#before_script:
 # - npm install -g gulp

script:
  - hexo generate

after_script:
  - cd ./public
  - git init
  - git config user.name "GuessEver"
  - git config user.email "guessever@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - source
env:
 global:
   - GH_REF: github.com/QKTeam/qkteam.github.io.git
